language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
after_success: npm run coveralls
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: 14
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
